version: '3.1'
services:
  web:
    build: .
    command: start
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/opt/odoo/data
      - odoo-web-config:/opt/odoo/etc
      - odoo-web-addons:/opt/odoo/additional_addons
    environment:
      - ODOO_DB_PASSWORD=odoo
      - ADDONS_REPO=https://github.com/r00ters/odoo_OCA_l10n-italy.git
      - ADDONS_REPO_BRANCH=16.0
      - FETCH_OCA_DEPENDENCIES=True
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-web-config:
  odoo-web-addons:
  odoo-db-data:
